// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMDLO4a-dq8ZvlkML-hmRkmQuiKdhLx48',
    appId: '1:1015071636195:web:93d8656a5a5fed69f4e3d6',
    messagingSenderId: '1015071636195',
    projectId: 'anitier2-b527d',
    authDomain: 'anitier2-b527d.firebaseapp.com',
    storageBucket: 'anitier2-b527d.firebasestorage.app',
    databaseURL: 'https://anitier2-b527d-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-XQd6j5FCvV555VCenYmU6DJSltsEF7M',
    appId: '1:1015071636195:android:1a9067d4c3ce6914f4e3d6',
    messagingSenderId: '1015071636195',
    projectId: 'anitier2-b527d',
    storageBucket: 'anitier2-b527d.firebasestorage.app',
    databaseURL: 'https://anitier2-b527d-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuaFCDueGvRX-H6VnL5BGhZL2HIoJmf6w',
    appId: '1:1015071636195:ios:bc2c3340aebfc261f4e3d6',
    messagingSenderId: '1015071636195',
    projectId: 'anitier2-b527d',
    storageBucket: 'anitier2-b527d.firebasestorage.app',
    iosClientId:
        '1015071636195-88bafoee7oi76c93524d8mbe60cte2ok.apps.googleusercontent.com',
    iosBundleId: 'com.yonasoft.anitier2',
    databaseURL: 'https://anitier2-b527d-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuaFCDueGvRX-H6VnL5BGhZL2HIoJmf6w',
    appId: '1:1015071636195:ios:bc2c3340aebfc261f4e3d6',
    messagingSenderId: '1015071636195',
    projectId: 'anitier2-b527d',
    storageBucket: 'anitier2-b527d.firebasestorage.app',
    iosClientId:
        '1015071636195-88bafoee7oi76c93524d8mbe60cte2ok.apps.googleusercontent.com',
    iosBundleId: 'com.yonasoft.anitier2',
    databaseURL: 'https://anitier2-b527d-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMDLO4a-dq8ZvlkML-hmRkmQuiKdhLx48',
    appId: '1:1015071636195:web:26e45ebd50c65c99f4e3d6',
    messagingSenderId: '1015071636195',
    projectId: 'anitier2-b527d',
    authDomain: 'anitier2-b527d.firebaseapp.com',
    storageBucket: 'anitier2-b527d.firebasestorage.app',
    databaseURL: 'https://anitier2-b527d-default-rtdb.firebaseio.com/',
  );
}
